[build]
  base = "project/"
  publish = "build-output/"
  command = "npm run build"

[context.production]
  publish = "output/"
  command = "make publish"
  environment = { NODE_VERSION = "14.15.3" }


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


[functions]
  directory = "functions/"